appsite/urls.py
from django.urls import path
from . import views

app_name = 'appsite'

urlpatterns = [
    path('', views.teste, name='teste'),
    path('index/', views.index, name='index'),
    path('signin/', views.signIn, name='signin'),
    path('signup/', views.signUp, name='signup'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('exibe/<int:id>/', views.exibe, name='exibe'),
    path('edita/', views.edita, name='edita'),
    path('remove/', views.remove, name='remove'),
    path('busca/', views.busca, name='busca')
]

projeto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from appsite.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appsite/', include('appsite.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('', index)
]

appsite/models.py
from django.db import models
#from django.conf import settings
from projeto import settings

class Language(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

class Projeto(models.Model):
    autor = models.CharField(max_length=20)
    nomeProjeto = models.CharField(max_length=20)
    linguagem = models.ManyToManyField('Language')

    def __str__(self):
        return self.nomeProjeto

    def linguagens(self):
        return "\n".join([i.nome for i in self.linguagem.all()])

appsite/forms.py
from decimal import Decimal
from django import forms
from django.core.validators import RegexValidator
from projeto import settings
from .models import Projeto, Language

class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = ('projeto_id', 'autor', 'linguagem', 'nomeProjeto')


    projeto_id = forms.CharField(widget=forms.HiddenInput(), required=False)

    autor = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '120'}),
    )

    linguagem = forms.ModelMultipleChoiceField(queryset=Language.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled', 'maxlength': '120'})
    )    

    nomeProjeto = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '120'}),
    )

class RemoveProdutoForm(forms.Form):
    class Meta:
        fields = ('projeto_id')

    projeto_id = forms.CharField(widget=forms.HiddenInput(), required=True)

appsite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse
from .forms import ProjetoForm, RemoveProdutoForm
from .models import Projeto, Language
from carrinho.forms import AdicionaItem
from carrinho.views import adiciona
#from appsite.models import Image

def teste(request):
    return HttpResponse("Servidor ativo")

def index(request):
    return render(request, 'appsite/index.html')

def signIn(request):
    return render(request, 'appsite/sign_in.html')

def signUp(request):
    #imagem = get_object_or_404(Image, pk=2)
    return render(request, 'appsite/sign_up.html')

def busca(request):
    projetos = Projeto.objects.all()
    if request.method == 'POST':
        form = AdicionaItem(request.POST)
        if form.is_valid():
            return adiciona(request, form.cleaned_data['projeto_id'])
    else:
        form = AdicionaItem(auto_id=False)
    return render(request, 'appsite/busca.html', {'projetos': projetos, 'form': form})

def cadastro(request):
    
    projeto_id = request.POST.get('projeto_id')

    if request.POST:
        # Se o parâmetro veio, trata-se de uma alteração.
        if projeto_id:
            #acao = 'alteracao'
            # Recupera um objeto Projeto ou gera o erro 404
            projeto = get_object_or_404(Projeto, pk=projeto_id)

            # Como se trata de uma alteração, o objeto ProjetoForm é instanciado utilizando
            # os dados provenientes do banco de dados (instance=produto) e, em seguida,
            # essas informações são atualizadas utilizando os dados submetidos pelo usuário (request.POST).
            form_projeto = ProjetoForm(request.POST, instance=projeto)
        else:
            #acao = 'inclusao'
            form_projeto = ProjetoForm(request.POST)

        if form_projeto.is_valid():
            # O método save() de ModelForm salva o produto (inclui ou altera) no banco de dados e retorna
            # um objeto do tipo Projeto.
            projeto = form_projeto.save()

            # Se a variável projeto_id for diferente de None então trata-se de uma alteração
            if projeto_id:
                # Gera uma mensagem que será exibida pela página exibe_produto.html através do framework de mensagens.
                messages.add_message(request, messages.INFO, 'Projeto alterado com sucesso.')
            else:
                messages.add_message(request, messages.INFO, 'Projeto cadastrado com sucesso.')

            # Aqui efetuamos um redirect para evitar que um mesmo produto seja cadastrado mais
            # de uma vez caso o usuário aperte a tecla F5 após cadastrar o produto.
            return redirect('appsite:exibe', id=projeto.id)
    else:
        # Ao chegar uma requisição do tipo GET, a página cadastra_produto.html é exibida.
        #acao = 'inclusao'
        form_projeto = ProjetoForm()

    #form_projeto = ProjetoForm()
    context = {'form': form_projeto, }
    return render(request, 'appsite/cadastro.html', context)

def exibe(request, id):
    obj = get_object_or_404(Projeto, pk=id)    
    remove_projeto_form = RemoveProdutoForm(initial={'projeto_id': id})
    projeto = {'projeto': obj, 'linguagem': obj.linguagem.all(), 'remove_projeto_form': remove_projeto_form,}
    return render(request, 'appsite/exibe.html', projeto)

def edita(request):
    projeto = get_object_or_404(Projeto, pk=id)
    formProjeto = ProjetoForm(instance=projeto)
    formProjeto.fields['projeto_id'].initial = projeto.id
    return render(request, 'produto/cadastra_produto.html', {'form': formProjeto, 'acao': 'alteracao'})

def remove(request):
    remove_projeto_form = RemoveProdutoForm(request.POST)
    if remove_projeto_form.is_valid():
        projeto_id = remove_projeto_form.cleaned_data['projeto_id']
        projeto = get_object_or_404(Projeto, pk=projeto_id)
        projeto.delete()
        messages.add_message(request, messages.INFO, 'Projeto removido com sucesso.')
        return render(request, 'appsite/exibe.html', {'projeto': projeto,
                                                              'remove_projeto_form': None})
    else:
        raise ValueError('Ocorreu um erro inesperado ao tentar remover um produto')

appsite/templates/appsite/busca.html
{% extends 'base.html' %}

{% load static %}

{% block title %} <title>Busca</title> {% endblock %}
{% block includes %}<link href="{% static 'appsite/css/estilos.css'%}" rel="stylesheet">{% endblock %}


{% block corpo %}
    <div class="container">
        <table class="table table-striped table-responsive table-bordered table-sm" id="tabela" style="width: 100%; margin: 20pt 0">
            <thead class="">
                <tr>
                    <th class="text-center" scope="col">Id</th>
                    <th class="text-center" scope="col">Autor</th>
                    <th class="text-center" scope="col">Nome do Projeto</th>
                    <th class="text-center" scope="col">Linguagens</th>
                    <th class="text-center" scope="col">Adicionar ao carrinho</th>
                </tr>
            </thead>
            <tbody id="tabela-corpo">
                {% for x in projetos %}
                <tr class="">
                    <td class="text-center" scope="row" width="10%">{{ x.id }}</td>
                    <td class="text-center" scope="row" width="25%">{{ x.autor }}</td>
                    <td class="text-center" scope="row" width="25%"><a href="{% url 'appsite:exibe' x.id %}" id="nome_projeto">{{ x.nomeProjeto }}</a></td>
                    <td class="text-center" scope="row" width="25%">
                        {% for y in x.linguagem.all %}
                        {{ y.nome }}
                        {% endfor %}
                    </td>
                    <td class="text-center" scope="row" width="30%">
                        <form method="POST" novalidate>
                            {% csrf_token %}
                            {{ form.projeto_id }}
                            <button type="submit" class="btn btn-sm btn-dark">Adicionar</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}       
            </tbody>
        </table>
    </div>
        
{% endblock %}

{% block domready %}
    $('#tabela tr').each(function(){
        let valor = $(this).find('td:first-child').text()
        $(this).find('td:last-child>form>input:nth-child(2)').val(valor)
        let valor2 = $(this).find('td:last-child>form>input:nth-child(2)').val()
        console.log(valor)
        console.log(valor2)
    })
{% endblock %}

appsite/templates/appsite/cadastro.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Cadastro</title>{% endblock %}
{% block includes %}<link href="{% static 'appsite/css/estilos.css'%}" rel="stylesheet">{% endblock %}

{% block corpo %}
        
    <div class="container">
        <p class="h3" style="margin: 20pt 10pt">Cadastro</p>

        <form action="" class="" method="POST">
            {% csrf_token %}
            <div class="form-group col-4">
                <label for="">Autor</label>
                {# <input type="text" name="" id="" class="form-control" placeholder="" aria-describedby="helpId"> #}
                {{ form.autor }}
                <small id="helpId" class="text-muted">Help text</small>
            </div>

            <div class="container form-group">
                <label for="">Linguagem</label>
                <div>
                    {{ form.linguagem }}
                
                    <!-- <div class="form-check form-check-inline">                        
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.java }}
                        <label class="form-check-label" for="">Java</label>
                    </div>
                    <div class="form-check form-check-inline">                        
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.c }}
                        <label class="form-check-label" for="">C/C++</label>
                    </div>
                    <div class="form-check form-check-inline">                        
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.python }}
                        <label class="form-check-label" for="">Python</label>
                    </div>
                    <div class="form-check form-check-inline">                        
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.javascript }}
                        <label class="form-check-label" for="">Javascript</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.html }}
                        <label class="form-check-label" for="">HTML</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.php }}
                        <label class="form-check-label" for="">PHP</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.ruby }}
                        <label class="form-check-label" for="">Ruby</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.vb }}
                        <label class="form-check-label" for="">Visual Basic .NET</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.sql }}
                        <label class="form-check-label" for="">PL/SQL</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {# <input class="form-check-input" type="checkbox" value="" id=""> #}
                        {{ form.swift }}
                        <label class="form-check-label" for="">Swift</label>
                    </div> -->
                </div>
            </div>
            
            <div class="form-group col-4">
                <label for="">Nome do Projeto</label>
                {# <input type="text" name="" id="" class="form-control" placeholder="" aria-describedby="helpId"> #}
                {{ form.nomeProjeto }}
                <small id="helpId" class="text-muted">Help text</small>
            </div>
            {% csrf_token %}
            <button type="submit" class="btn btn-dark" style="margin-left: 12pt">Cadastrar</button>
            
        </form>
    </div>
{% endblock %}     
    
    

appsite/templates/appsite/exibe.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Exibe</title>{% endblock %}
{% block includes %}<link href="{% static 'appsite/css/estilos.css'%}" rel="stylesheet">{% endblock %}

{% block corpo %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary" role="alert" style="margin: 30pt 0">
                <strong>{{ message }}</strong>}
            </div>
            {% endfor %}
        {% endif %}

        <div style="margin: 30pt 0">
            <p class="h3">Projeto</p>

            <p class="h5">Autor: </p>
            {{ projeto.autor }}
            <p class="h5">Nome do Projeto:</p>
            {{ projeto.nomeProjeto }}
            <p class="h5">Linguagens:</p>
            {% for x in linguagem %}
                {{ x.nome }}
            {% endfor %}            
        </div>
    
    {% if remove_projeto_form %}
    <form action="{% url 'appsite:remove' %}" method="POST" id="remove_projeto" novalidate>
        {% csrf_token %}

        <button id="btn_remove" class="btn btn-danger">Remover</button>
    </form>

    <form action="{% url 'appsite:edita' %}" method="POST" id="edita_projeto" novalidate>
        {% csrf_token %}

        <button id="btn-edita" class="btn btn-dark">Edita</button>
    </form>
            
    </div>
    {% endif %}
{% endblock %}

{% block domready %}
    $("#btn_remove").click(function() {
        $("#remove_projeto").append('{{ remove_projeto_form.projeto_id }}')
        $("#remove_projeto").submit()
    })

    $('#btn-edita').click(function () {
        $('#edita_projeto').append('{{ remove_projeto_form.projeto_id }}')
        $('#edita_projeto').submit()
    })
    
{% endblock %}

appsite/templates/appsite/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>GitHub</title>{% endblock %}

{% block includes %}<link href="{% static 'appsite/css/estilos.css'%}" rel="stylesheet">{% endblock %}

{% block corpo %}
    <div class="jumbotron-codelines">
        <div class="container d-md-flex justify-content-center section-2">
            <div class="col-md-4">
                <h1>Built for developers</h1>
                <p>GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside 28 million developers.</p>
            </div>
            
            <div class="col-md-4 text-gray border rounded submit-signup" style="padding-right: 20px; padding-left: 20px;">
                <form action="" class="form-group">
                    <div class="form-item">
                        <label for="username">Username</label>
                        <input type="username" name="" id="username" class="form-control" placeholder="Pick a username">
                    </div>

                    <div class="form-item">
                        <label for="email">Email</label>
                        <input type="email" name="" id="email" class="form-control" placeholder="you@example.com">
                    </div>

                    <div class="form-item">
                        <label for="password">Password</label>
                        <input type="password" name="" id="password" class="form-control" placeholder="Create a password">
                    </div>

                    <div class="form-item">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="">
        <div class="container text-center sections">
            <h2>Try GitHub Entreprise</h2>
            
            <p>Use GitHub on-premises with your own servers or in a private cloud with GitHub Enterprise. 
                Improve your developer efficiency with flexible deployment options, centralized permissions, 
                hundreds of integrations, technical support, and more.
            </p>

            <button type="button" class="btn btn-primary btn-lg">Contact Sales</button>

        </div>
    </div>


    <div class="container text-center sections">
        <p>More than 1.8 million businesses and organizations use GitHub</p>

        <ul class="list-style-none d-flex justify-content-center flex-wrap mt-2 mt-md-3">
            <li> <img src="{% static 'appsite/images/logos/airbnb-logo.png' %}" class="logo-cinza" alt="AirBnB logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/sap-logo.png' %}" class="logo-cinza" alt="Sap logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/ibm-logo.png' %}" class="logo-cinza" alt="IBM logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/google-logo.png' %}" class="logo-cinza" alt="Google logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/paypal-logo.png' %}" class="logo-cinza" alt="PayPal logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/bloomberg-logo.png' %}" class="logo-cinza" alt="Bloomberg logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/spotify-logo.png' %}" class="logo-cinza" alt="Spotify logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/swift-logo.png' %}" class="logo-cinza" alt="Swift logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/facebook-logo.png' %}" class="logo-cinza" alt="Facebook logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/node-logo.png' %}" class="logo-cinza" alt="NodeJS logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/nasa-logo.png' %}" class="logo-cinza" alt="Nasa logo"> </li>
            <li> <img src="{% static 'appsite/images/logos/walmart-logo.png' %}" class="logo-cinza" alt="walmart-logo"> </li>
        </ul> 
    </div>


    <div class="container text-center sections">
        <p>GitHub for teams</p>
        <h1>A better way to work together</h1>
        <p>GitHub brings teams together to work through problems, move ideas forward, and learn from each other along the way.</p>
        <button type="button" class="btn btn-outline-primary">Sign up your team </button>
    </div>


    <div class="container-xl">
        <div class="d-md-flex">
            <div class="col-md-6">
                <img src="{% static 'appsite/images/index/home-illo-team.svg' %}" alt="" class="d-block">
            </div>
            <div class="col-md-6 flex-column">
                <div class="caixa-texto">
                    <h5>Write better code</h5>
                    <p>Collaboration makes perfect. The conversations and code reviews that happen in Pull Requests help your team 
                        share the weight of your work and improve the software you build. </p>
                </div>
                <div class="caixa-texto">
                    <h5>Manage your chaos</h5>
                    <p>Take a deep breath. On GitHub, project management happens in Issues and Projects, right alongside your code. 
                        All you have to do is mention a teammate to get them involved. </p>
                </div>
                <div class="caixa-texto">
                    <h5>Find the right tools</h5>
                    <p>Browse and buy apps from GitHub Marketplace with your GitHub account. Find the tools you like or discover new 
                        favorites—then start using them in minutes. </p>
                </div>
            </div>
        </div>
    </div>


    <div class="container text-center sections">
        <p>Security and administration</p>
        <h1>Boxes? Check.</h1>
        <p>We worry about your administrative and security needs so you don’t have to. From flexible hosting to authentication 
            options, GitHub can help you meet your team’s requirements.</p>
        <button type="button" class="btn btn-outline-primary">See how GitHub works for business</button>            
    </div>

    <div class="container">
        <div class="d-md-flex">
            <div class="col-md-6">
                <div class="caixa-texto">
                    <h5>Code security</h5>
                    <p>Prevent problems before they happen. Protected branches, signed commits, and required status checks protect 
                        your work and help you maintain a high standard for your code.</p>
                </div>
                <div class="caixa-texto">
                    <h5>Access controlled</h5>
                    <p>Encourage teams to work together while limiting access to those who need it with granular permissions and 
                        authentication through SAML/SSO and LDAP.</p>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static 'appsite/images/index/home-illo-business.png' %}" alt="" class="encaixe-largura">
            </div>
        </div>
    </div>
    

    <div class="container text-center sections">
        <p>Integrations</p>
        <h1>Build on GitHub</h1>
        <p>Customize your process with GitHub apps and an intuitive API. Integrate the tools you already use or discover new favorites
            to create a happier, more efficient way of working.</p>
        <button type="button" class="btn btn-outline-primary">Learn about integrations</button>
    </div>


    <div class="container text-center sections">
        <p>Community</p>
        <h5>Welcome home, developers</h5>
        <p>GitHub is home to the world’s largest community of developers and their projects...</p>
        <div>
            <!-- barra de rolagem -->
        </div>
        <p>...whether you’re making your first commit or sending a Rover to Mars, there’s room for you here, too.</p>
    </div>

    <div>
        <div class="d-flex flex-row scroll-images">
            <div class="border d-inline-flex">
                <img src="{% static 'appsite/images/index/ariya.png' %}" alt="" class="float-left" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Ariya Hidayat</6>
            </div>
            <div class="border d-inline-flex">
                <img src="{% static 'appsite/images/index/freakboy3742.png' %}" alt="" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Russell Keith-Magee</6>                    
            </div>
            <div class="border d-inline-flex">            
                <img src="{% static 'appsite/images/index/mailchimp.png' %}" alt="" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Russell Keith-Magee</6>
            </div>
            <div class="border d-inline-flex">
                <img src="{% static 'appsite/images/index/kris-nova.png' %}" alt="" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Kris Nova</6>
            </div>
            <div class="broder d-inline-flex">
                <img src="{% static 'appsite/images/index/yyx990803.png' %}" alt="" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Evan You</6>
            </div>
            <div class="broder d-inline-flex">
                <img src="{% static 'appsite/images/index/mapbox.png' %}" alt="" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Mapbox</6>
            </div>
            <div class="broder d-inline-flex">
                <img src="{% static 'appsite/images/index/jessfraz.png' %}" alt="" style="height: 150px">
                <h6 class="align-self-center text-center text-justify legenda">Jess Fazelle</6>
            </div>
        </div>
    </div>


    <div class="container sections">
        <div class="d-md-flex">
            <div class="col-md-6"></div>

            <div class="col-md-6 flex-column">
                <div class="caixa-texto">
                    <p>GitHub’s users create and maintain influential technologies alongside the world’s largest open source community</p>
                </div>
                <div class="caixa-texto">
                    <p>Developers use GitHub for personal projects, from experimenting with new programming languages to hosting their life’s work.</p>
                </div>
                <div class="caixa-texto">
                    <p>Business of all sizes use GitHub to support their development process and to securely build software.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="bg-dark footer-pad">
        <div class="container" style="margin-bottom: 75px">
            <div class="text-center" style="padding-left: 100px; padding-right: 100px">
                <h2 class="text-white">Get started for free — join the millions of developers already using GitHub to share their code, work together, 
                    and build amazing things. </h2>
            </div>
        </div>
            
        <div class="container-xl">
            <div class="d-md-flex">
                <div class="form-group form-control-lg col-md-3">
                    <input type="username" name="" id="username-bot" class="form-control" placeholder="Pick a username">
                </div>
                <div class="form-group form-control-lg col-md-3">
                    <input type="email" name="" id="email-bot" class="form-control d-md-inline" placeholder="Your email address">
                </div>
                <div class="form-group form-control-lg col-md-3">
                    <input type="password" name="" id="password-bot" class="form-control d-md-inline" placeholder="Create a password">
                </div>
                <div class="form-group form-control-lg col-md-3">
                    <button type="button" class="form-group btn btn-primary btn-block">Sign up for GitHub</button>
                </div>
            </div>
        </div>           
    </div>

{% endblock %}

appsite/templates/appsite/sign_in.html
{% load static %}

<!doctype html>
<html>
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'appsite/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'appsite/css/estilos.css' %}">
		<link rel="stylesheet" href="{% static 'appsite/css/sign_in.css' %}">
		

		<title>Sign in</title>
	</head>
	<body>
		<div class="container container-sign-in">
			<div class="d-flex logo">
				<div class="mx-auto">
					<svg height="48" class="octicon octicon-mark-github" viewBox="0 0 16 16" version="1.1" width="48" aria-hidden="true"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
				</div>
			</div>

			<div class="d-flex container-sign-in">
				<div class="mx-auto" style="margin: 10px auto">
					<h4>Sign in to GitHub</h4>
				</div>
			</div>

			<div class="border rounded page-sign-in sign-in shadow-sm mx-auto font-weight-bold">
				<form action="">
					<label for="email">Username or email address</label>
					<input type="text" name="" id="email" class="form-control form-group">

					<label for="senha">Senha</label>
					<input type="text" name="" id="senha" class="form-control form-group">
				</form>
				
				<button type="button" class="btn btn-primary btn-block">Sign in</button>
			</div>

			<div class="border rounded page-sign-in shadow-sm mx-auto">
				<div class="abc text-center">
					<p class="align-self-center">New to GitHub? <a href="">Create an account</a></p>				
				</div>			
			</div>

			<div class="text-center f-margin">
				<div class="d-inline-flex">
					<p class="footer"><a href="">Terms</a></p>
					<p class="footer"><a href="">Privacy</a></p>
					<p class="footer"><a href="">Security</a></p>
					<p class="footer"><a href="">Contact GitHub</a></p>
				</div>
			</div>
		</div>

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>