appsite/urls.py
from django.urls import path
from . import views

app_name = 'appsite'

urlpatterns = [
    path('', views.teste, name='teste'),
    path('index/', views.index, name='index'),
    path('signin/', views.signIn, name='signin'),
    path('signup/', views.signUp, name='signup'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('exibe/<int:id>/', views.exibe, name='exibe'),
    path('edita/', views.edita, name='edita'),
    path('remove/', views.remove, name='remove'),
    path('busca/', views.busca, name='busca')
]

carrinho/urls.py
from . import views
from django.urls import path

app_name = 'carrinho'

urlpatterns = [
    path('', views.carrinho, name='carrinho'),
    path('atualizacao/quantidade/', views.carrinho, name='atualizacao'),
    path('atualizacao/remocao/', views.carrinho, name='remocao')
]

projeto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from appsite.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appsite/', include('appsite.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('', index)
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'appsite/css/bootstrap.css'%}">
    <link href="{% static 'appsite/open-iconic/font/css/open-iconic-bootstrap.css'%}" rel="stylesheet">

    {% block title %} {% endblock %}
    {% block includes %} {% endblock %}

</head>
<body>
    <nav class="navbar bg-dark navbar-dark navbar-expand-md">
        <div class="container">
            <a class="navbar-brand logo-invertido" href="{% url 'appsite:index' %}">
                <svg height="32" class="octicon octicon-mark-github" viewBox="0 0 16 16" version="1.1" width="32" aria-hidden="true"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menu">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'appsite:cadastro' %}">Cadastro</a>
                    <a class="nav-item nav-link" href="{% url 'appsite:busca' %}">Busca</a>
                    <a class="nav-item nav-link" href="#">Explore</a>
                    <a class="nav-item nav-link" href="#">Marketplace</a>
                    <a class="nav-item nav-link" href="#">Pricing</a>                        
                </div>
                <div class="nav-item">
                    <span><a class="" href="{% url 'appsite:signin' %}">Sign in</a></span>
                        or
                        <span><a class="" href="{% url 'carrinho:carrinho' %}">Carrinho</a></span>
                </div>                    
            </div>                        
        </div>        
    </nav>

    {% block corpo %}

    {% endblock %}

    <footer class="container" style="margin: 50px auto">
        <div class="d-md-flex">
            <div class="col-md-4">                    
        </div>

        <div class="col-md-4">
            <div class="row">
                <div class="col">
                    <ul class="list-style-none">
                        <li>Product</li>
                        <li>Features</li>
                        <li>Security</li>
                        <li>Business</li>
                        <li>Case studies</li>
                        <li>Pricing</li>
                        <li>Resources</li>
                    </ul>
                </div>
                <div class="col">
                    <ul class="list-style-none">
                        <li>Platform</li>
                        <li>Developer API</li>
                        <li>Partners</li>
                        <li>Atom</li>
                        <li>Electron</li>
                        <li>GitHub Desktop</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="row">
                <div class="col">
                    <ul class="list-style-none">
                        <li>Support</li>
                        <li>Help</li>
                        <li>Community Forum</li>
                        <li>Training</li>
                        <li>Status</li>
                        <li>Contact GitHub</li>
                    </ul>
                </div>
                <div class="col">
                    <ul class="list-style-none">
                        <li>Company</li>
                        <li>About</li>
                        <li>Blog</li>
                        <li>Careers</li>
                        <li>Press</li>
                        <li>Shop</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'appsite/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'appsite/js/popper.js' %}"></script>
    <script src="{% static 'appsite/js/bootstrap.js' %}"></script>
    <script src="{% static 'appsite/js/script.js' %}"></script>
    <script>
        $(document).ready(function(){
            {% block domready %}

            {% endblock %}
        })
    </script>
</body>
</html>